### ISSUE TITLE
hide wolf collar crash my game

### ISSUE THREAD

**Issue by ghost** [PanJohnny/NoArrowsInYou#6]

**Comment by PanJohnny** [comment]
Which version of Minecraft and the modification have you used? And can you please send me the crash report?

Or just send me the crash report. Please use something like: https://mclo.gs/

**Comment by ghost** [comment]
1.20.1, hide wolf collar
crash report: [link](https://mclo.gs/75GuflU)

**Comment by PanJohnny** [comment]
The error seems to be caused by OptiGUI. I can't see any correlation with NAIY.

**Comment by PanJohnny** [comment]
Also the error you sent me is a startup error. Which can't be caused by clicking a button.

**Comment by ghost** [comment]
this one: [link](https://mclo.gs/cTbpUEN)
the cat collar works fine, does it matter?

**Comment by PanJohnny** [comment]
I have found the issue. So sorry for the wait, the next version will contain the patch. It should be available in couple of hours.

**Comment by ghost** [comment]
yay thank u

**Comment by ghost** [comment]
can u make 1.20.1 pls

**Comment by PanJohnny** [comment]
It should support 1.20.* - any 1.20 version

**Comment by PanJohnny** [comment]
See here: https://github.com/PanJohnny/NoArrowsInYou/blob/1.20.1/src/main/resources/fabric.mod.json#L28

I am locking this issue
